BHoMUpgrader/IConverter.cs, BHoMUpgrader/Upgrader.cs, BHoMUpgrader30/BHoMUpgrader30.csproj, BHoMUpgrader30/Converter/_Interface.cs, BHoMUpgrader30/TypeConverter.cs
https://github.com/BHoM/BHoM_Engine/pull/1291
Closes #3
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue3_deserialise_Test.gh?csf=1&e=SvuDH8
This is a follow up to PR #2. See https://github.com/BHoM/Versioning_Toolkit/pull/2#issuecomment-544871222 for more details
=> Provide an update strategy for change of namespace and/or class name

BHoMUpgrader/Properties/AssemblyInfo.cs, Versioning_oM/Properties/AssemblyInfo.cs
=> AssemblyFileVersion changed to 3.1.0.0

BHoMUpgrader/Converter.cs, BHoMUpgrader/Upgrader.cs
Align the versioning code with https://github.com/BHoM/BHoM_UI/pull/247
See https://github.com/BHoM/BHoM_UI/pull/247 for more details
=> Improve support for decentralised versioning

BHoMUpgrader/BHoMUpgrader.csproj, BHoMUpgrader/packages.config, PostBuild/PostBuild.csproj, PostBuild/packages.config
No dependency but would be nice to merge at the same time as https://github.com/BHoM/BHoM_Engine/pull/1876
Closes #84
=> Upgrade Mongo Bson package

BHoMUpgrader/Properties/AssemblyInfo.cs, PostBuild/Properties/AssemblyInfo.cs, Versioning_oM/Properties/AssemblyInfo.cs
Closes #98
Found out when trying to use `PreviousVersionAttribute` on a method, but not sure how would that be added as a test file 😉 
- Assembly versions updated
This PR is critical, without it Versioning seems not to work. @adecler, could you please double check if I did not miss any project?
=> Assembly versions updated

BHoMUpgrader40/Converter.cs
https://github.com/BHoM/BHoM/pull/1026
See test file and notes in https://github.com/BHoM/BHoM/pull/1026
=> Adding versioning for BoundaryRepresentation 

BHoMUpgrader40/Converter.cs
Closes #103
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FVersioning%5FToolkit%2FVersioning%5FToolkit%2DIssue103%2DRevitIdentifiers&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- versioning added for `BH.oM.Adapters.Revit.Parameters.RevitIdentifiers`
=> Versioning added for BH.oM.Adapters.Revit.Parameters.RevitIdentifiers

BHoMUpgrader40/Converter.cs
https://github.com/BHoM/Revit_Toolkit/pull/906
=> Updated RevitIdentifiers versioning

BHoMUpgrader40/Converter.cs
Closes #100 
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FStructure%5FEngine%2FStructure%5FEngine%2DIssue2014%2DMapTaperedProfilesToBars
=> Added versioning for TaperedProfile adding interpolationOrder to serialised TaperedProfiles

BHoMUpgrader40/Converter.cs
https://github.com/BHoM/BHoM/pull/1108
Closes #107 
Handles versioning for Space objects
[SpaceUpgrade.zip](https://github.com/BHoM/Versioning_Toolkit/files/5621821/SpaceUpgrade.zip)
=> Versioning for Space objects

BHoMUpgrader40/Converter.cs
Closes #111 
Fixing typo in class name calling converter.
=> Fix typo in Converter

BHoMUpgrader40/Upgrades.json, BHoMUpgrader41/App.config, BHoMUpgrader41/BHoMUpgrader41.csproj, BHoMUpgrader41/Converter.cs, BHoMUpgrader41/Program.cs, BHoMUpgrader41/Properties/AssemblyInfo.cs, BHoMUpgrader41/Upgrades.json, Versioning_Toolkit.sln
Closes #119 
To adds the versioning support for version 4.1 and freezes the list of upgrades for version 4.0 following this procedure: https://github.com/BHoM/Versioning_Toolkit/wiki/End-of-milestone-procedure
=> Migrate to version 4.1

BHoMUpgrader/Properties/AssemblyInfo.cs, PostBuild/Properties/AssemblyInfo.cs, Versioning_oM/Properties/AssemblyInfo.cs
=> Update AssemblyFileVersion to 4.1.0.0

BHoMUpgrader41/Converter.cs
Closes nothing 🙈 
See https://github.com/BHoM/Revit_Toolkit/pull/977.
- versioning added for `RevitIdentifiers`
=> Versioning added for RevitIdentifiers

BHoMUpgrader40/Converter.cs
https://github.com/BHoM/BHoM/pull/1207
Closes #
=> Resolve versioning for MEP DuctSectionProperty from 3.3 to current

BHoMUpgrader41/Converter.cs, BHoMUpgrader41/Upgrades.json
Closes #
- add a custom upgrader for HarpoonObject in CFD_Toolkit
=> Enclosed volume harpoon object upgrade

BHoMUpgrader/Properties/AssemblyInfo.cs, BHoMUpgrader41/Upgrades.json, BHoMUpgrader42/App.config, BHoMUpgrader42/BHoMUpgrader42.csproj, BHoMUpgrader42/Converter.cs, BHoMUpgrader42/Program.cs, BHoMUpgrader42/Properties/AssemblyInfo.cs, BHoMUpgrader42/Upgrades.json, PostBuild/Properties/AssemblyInfo.cs, Versioning_Toolkit.sln
Closes #151
Adds the versioning support for version 4.2 and freezes the list of upgrades for version 4.1 following this procedure: https://github.com/BHoM/Versioning_Toolkit/wiki/End-of-milestone-procedure
To be merged once we have completed the transition to BHoM 4.2
=> Migrate to version 4.2

BHoMUpgrader42/Converter.cs
[BHoM PR 1229](https://github.com/BHoM/BHoM/pull/1229)
Closes [BHoM 1224](https://github.com/BHoM/BHoM/issues/1224)
=> Added upgrader for ContourLoadSet and UniformLoadSet

BHoMUpgrader42/Converter.cs
=> Upgrade AutoTimescale

BHoMUpgrader42/Upgrades.json, BHoMUpgrader43/App.config, BHoMUpgrader43/BHoMUpgrader43.csproj, BHoMUpgrader43/Converter.cs, BHoMUpgrader43/Program.cs, BHoMUpgrader43/Properties/AssemblyInfo.cs, BHoMUpgrader43/Upgrades.json, PostBuild/Properties/AssemblyInfo.cs, Versioning_Toolkit.sln
Closes #164
Adds the versioning support for version 4.3 and freezes the list of upgrades for version 4.2 following this procedure: https://github.com/BHoM/Versioning_Toolkit/wiki/End-of-milestone-procedure
To be merged once we have completed the transition to BHoM 4.3
=> Migrate the Versioning toolkit to version 4.3

BHoMUpgrader43/Converter.cs, BHoMUpgrader43/Upgrades.json
https://github.com/BHoM/BHoM/pull/1248
Closes #161
=> Upgrade CableTray

BHoMUpgrader43/Converter.cs
https://github.com/BHoM/BHoM/pull/1267
Needed to resolve https://github.com/BHoM/Revit_Toolkit/issues/884
=> Versioning for RevitIdentifiers added

BHoMUpgrader/BHoMUpgrader.csproj, BHoMUpgrader30/App.config, BHoMUpgrader30/BHoMUpgrader30.csproj, BHoMUpgrader31/App.config, BHoMUpgrader31/BHoMUpgrader31.csproj, BHoMUpgrader32/App.config, BHoMUpgrader32/BHoMUpgrader32.csproj, BHoMUpgrader33/App.config, BHoMUpgrader33/BHoMUpgrader33.csproj, BHoMUpgrader40/App.config, BHoMUpgrader40/BHoMUpgrader40.csproj, BHoMUpgrader41/App.config, BHoMUpgrader41/BHoMUpgrader41.csproj, BHoMUpgrader42/App.config, BHoMUpgrader42/BHoMUpgrader42.csproj, BHoMUpgrader43/App.config, BHoMUpgrader43/BHoMUpgrader43.csproj, BHoMUpgrader50/App.config, BHoMUpgrader50/BHoMUpgrader50.csproj, PostBuild/App.config, PostBuild/PostBuild.csproj
Upgrade to .Net Framework 4.7.2 for projects that were targeting a lower framework
=> Upgrade .Net Framework to 4.7.2

BHoMUpgrader50/Converter.cs
=> Versioning of PinnedButtonInfo added

BHoMUpgrader50/Converter.cs
Closes #
See https://github.com/BHoM/Revit_Toolkit/pull/1127.
=> Versioning of Revit_Toolkit changes made in #1127

.ci/code/Versioning_Test/Helpers/CanReplaceMethodWithType.cs, .ci/code/Versioning_Test/Verify/FromJson.cs, .ci/code/Versioning_Test/Versioning_Test.csproj, BHoMUpgrader/Upgrader.cs, PostBuild/CopyUpgrades.cs, PostBuild/PostBuild.csproj
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729
=> Align with changes in oM and Engine on Reflection -> Base

BHoMUpgrader52/Converter.cs
Adding custom upgrader for TributaryRegion
=> Add custom upgrader for TributaryRegion

BHoMUpgrader52/Converter.cs
https://github.com/BHoM/BHoM/pull/1391
Adding custom converters for classes changed in the oM
=> Adding versioning for Lighting results

BHoMUpgrader30/BHoMUpgrader30.csproj, BHoMUpgrader31/BHoMUpgrader31.csproj, BHoMUpgrader32/BHoMUpgrader32.csproj, BHoMUpgrader33/BHoMUpgrader33.csproj, BHoMUpgrader40/BHoMUpgrader40.csproj, BHoMUpgrader41/BHoMUpgrader41.csproj, BHoMUpgrader42/BHoMUpgrader42.csproj, BHoMUpgrader43/BHoMUpgrader43.csproj, BHoMUpgrader50/BHoMUpgrader50.csproj, BHoMUpgrader51/BHoMUpgrader51.csproj, BHoMUpgrader52/BHoMUpgrader52.csproj, BHoMUpgrader53/BHoMUpgrader53.csproj
Fixes a CI issue when building beta artefacts that was identified at the end of last milestone.
=> Update csproject files to build locations for release mode

BHoMUpgrader/BHoMUpgrader.csproj, BHoMUpgrader/packages.config, PostBuild/PostBuild.csproj, PostBuild/packages.config
Closes https://github.com/BHoM/BHoM_Engine/issues/2948
=> Upgrade to Mongo version 2.18

BHoMUpgrader/Upgrader.cs
Removes whitespace added in #208
=> Remove whitespace

PostBuild/Program.cs
As discussed with @pawelbaran during testing of Revit Versioning.
=> Attempt to load Revit API if needed/existing in PostBuild

BHoMUpgrader62/Converter.cs
https://github.com/BHoM/BHoM/pull/1501
Closes #221 
Added method to converter to handle creating new Orientation Basis property from previous Direction vector property.
=> Added Luminaire Versioning for Orientation Property Change

BHoMUpgrader62/Converter.cs
https://github.com/BHoM/BHoM/pull/1506
=> Add versioning for InputAttribute

BHoMUpgrader/Upgrader.cs, BHoMUpgrader62/Converter.cs
In support of
https://github.com/BuroHappoldEngineering/StructuralEngineering_Toolkit/pull/498
Add custom upgrader for FloorDesign objects and FloorConfigurations
=> Upgrade floor design

BHoMUpgrader62/Converter.cs
https://github.com/BHoM/LadybugTools_Toolkit/pull/90
=> Add Versioning for SimulationResult for LadyBugTools

.ci/code/Versioning_Test/Versioning_Test.csproj, BHoMUpgrader62/BHoMUpgrader62.csproj, BHoMUpgrader63/BHoMUpgrader63.csproj
=> Fix project compliance for .ci Verification

BHoMUpgrader70/Converter.cs
https://github.com/BHoM/LadybugTools_Toolkit/pull/128
Closes #240
=> Versioning for changes to Ladybug Tools Toolkit

.ci/code/Versioning_Test/Properties/AssemblyInfo.cs, BHoMUpgrader30/Properties/AssemblyInfo.cs, BHoMUpgrader31/Properties/AssemblyInfo.cs, BHoMUpgrader32/Properties/AssemblyInfo.cs, BHoMUpgrader33/Properties/AssemblyInfo.cs, BHoMUpgrader40/Properties/AssemblyInfo.cs, BHoMUpgrader41/Properties/AssemblyInfo.cs, BHoMUpgrader42/Properties/AssemblyInfo.cs, BHoMUpgrader43/Properties/AssemblyInfo.cs, BHoMUpgrader50/Properties/AssemblyInfo.cs, BHoMUpgrader51/Properties/AssemblyInfo.cs, BHoMUpgrader52/Properties/AssemblyInfo.cs, BHoMUpgrader53/Properties/AssemblyInfo.cs, BHoMUpgrader60/Properties/AssemblyInfo.cs, BHoMUpgrader61/Properties/AssemblyInfo.cs, BHoMUpgrader62/Properties/AssemblyInfo.cs, BHoMUpgrader63/Properties/AssemblyInfo.cs, BHoMUpgrader70/Properties/AssemblyInfo.cs
This should not have been merged at this time and should be reverted.
=> Revert "Update AssemblyFileVersion to 7.1"

BHoMUpgrader30/BHoMUpgrader30.csproj, BHoMUpgrader31/BHoMUpgrader31.csproj, BHoMUpgrader32/BHoMUpgrader32.csproj, BHoMUpgrader33/BHoMUpgrader33.csproj, BHoMUpgrader40/BHoMUpgrader40.csproj, BHoMUpgrader41/BHoMUpgrader41.csproj, BHoMUpgrader42/BHoMUpgrader42.csproj, BHoMUpgrader43/BHoMUpgrader43.csproj, BHoMUpgrader50/BHoMUpgrader50.csproj, BHoMUpgrader51/BHoMUpgrader51.csproj, BHoMUpgrader52/BHoMUpgrader52.csproj, BHoMUpgrader53/BHoMUpgrader53.csproj, BHoMUpgrader60/BHoMUpgrader60.csproj, BHoMUpgrader61/BHoMUpgrader61.csproj, BHoMUpgrader62/BHoMUpgrader62.csproj, BHoMUpgrader63/BHoMUpgrader63.csproj, BHoMUpgrader70/BHoMUpgrader70.csproj, BHoMUpgrader71/BHoMUpgrader71.csproj, BHoMUpgrader72/BHoMUpgrader72.csproj, PostBuild/PostBuild.csproj
https://github.com/BHoM/BHoM/pull/1610
Fixes #255
=> Allow upgrader EXEs to also be DLLs

BHoMUpgrader81/Converter.cs
Changed structure of `SolarPanelTiltOptimisationCommand` (also renamed to `SolarRadiationPlotCommand`)
WIP until versioning passes
=> LadybugToolsToolkit versioning update

PostBuild/Properties/AssemblyInfo.cs
Closes #273
Bumps the version for PostBuild missed in milestone tickup
=> Update version for PostBuild .exe

BHoMUpgrader81/Converter.cs
=> LadybugTools_Toolkit versioning

BHoMUpgrader81/Converter.cs
Helps closing https://github.com/BHoM/Revit_Toolkit/issues/1542
=> Revit versioning tweaked

BHoMUpgrader81/Converter.cs
Helps closing https://github.com/BHoM/Revit_Toolkit/issues/1545
=> Another tweak to Revit versioning

.ci/code/Versioning_Test/Helpers/CanReplaceMethodWithType.cs, .ci/code/Versioning_Test/Helpers/DescriptionFromJson.cs, .ci/code/Versioning_Test/Properties/AssemblyInfo.cs, .ci/code/Versioning_Test/Verify/FromJson.cs
=> Uptick copyright of test project

BHoMUpgrader81/BHoMUpgrader81.csproj
Closes #294
Missed in 8.2 uptick. Required for 8.1 versioning to function
See https://github.com/BHoM/Versioning_Toolkit/pull/271/files#diff-b08fd2a963f4e46ebb39ad21b682432cce68aa9a97aeeffcb73b340c254b4c44 for reference
=> Fix missing       <CopyToOutputDirectory>Always</CopyToOutputDirectory> for upgrades

BHoMUpgrader82/Converter.cs
[BHoM-#1683](https://github.com/BHoM/BHoM/pull/1683)
Closes #
Add versioning after changes in `BH.oM.Security.Elements.CameraDevice`.
[GH script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Versioning_Toolkit/%23299-CameraDeviceUpgrade?csf=1&web=1&e=emhTAX)
=> Add `CameraDevice` custom versioning

BHoMUpgrades/CustomUpgrades/v82.cs
Supports https://github.com/BHoM/BHoM/pull/1687
Passing versioning check should be enough of verification.
=> RequirementResult versioned

BHoMUpgrades/BHoMUpgrades.csproj
Closes #306
See issue for more details
Just run the compliance checks
=> Fix project compliance
