BHoM/Versioning_Toolkit

- BHoMUpgrader/BHoMUpgrader.csproj
- BHoMUpgrader/IConverter.cs
- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader30/Converter/Version.cs
- BHoMUpgrader30/Converter/_Interface.cs
https://github.com/BHoM/BHoM_Engine/pull/1301
Closes #5
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue5_deserialise_Test.gh?csf=1&e=Ke9V5v
This is a follow up to PR #2. See https://github.com/BHoM/Versioning_Toolkit/pull/2#issuecomment-544871222 for more details
> Provide an upgrade strategy for the case where a class was modified internally

- BHoMUpgrader/IConverter.cs
- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader31/App.config
- BHoMUpgrader31/BHoMUpgrader31.csproj
- BHoMUpgrader31/MethodConverter.cs
- BHoMUpgrader31/ObjectConverter/_Interface.cs
- BHoMUpgrader31/Program.cs
- BHoMUpgrader31/Properties/AssemblyInfo.cs
- BHoMUpgrader31/TypeConverter.cs
- Versioning_Toolkit.sln
https://github.com/BHoM/BHoM_Engine/pull/1477
Closes #20
- for objects:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue21_BackwardCompatibilityTest.gh?csf=1&e=FuoX56
- for methods:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue7_MethodUpgradeTest_ForAdapters.gh?csf=1&e=mMnHaH
Same file as before and should give the same result. The difference is that the upgrades done for this files are now one level down the upgrader chain.
What you can do as a test is use the PR from the Engine (that correctly gets the assembly file version) and see that nothing gets upgraded properly. Then switch to this branch onV_TK and see that it works again.
The other test will …
> Add upgrader 3.1 and support for upgrader chains

- BHoMUpgrader31/TypeConverter.cs
Done to support https://github.com/BHoM/BHoM/pull/711
From my understanding though, this can be merged before the BHoM has been merged, as types are referenced by strings, and this will only get called when something goes wrong with deserialisation, hence, will only get called for old methods once the oM branch is merged. So, as long as we are sure on the change in BHoM (which I think we are) we can merge this PR straight away.
Closes #30
> Type upgrader for IBHoMFragment to IFragment

- BHoMUpgrader31/BHoMUpgrader31.csproj
- BHoMUpgrader31/MethodConverter.cs
- Versioning_Toolkit.sln
Refers to https://github.com/BHoM/BHoM_Engine/pull/1551
ClipPolylines is removed from Geometry_Engine and Version controlled via the MethodConverter. BooleanIntersection is the replacement method.
> Geometry_Engine: remove the ClipPolylines method

- BHoMUpgrader/Upgrader.cs
Closes #39 
Only get the Type part from the Type string by removing any part after the first ','
> Removing any non-type part from the type string

- BHoMUpgrader31/TypeConverter.cs
Closes #
The ETABS toolkit changes its definition of EtabsConfig to EtabsSettings which we want to version.
This PR adds a type converter which solves that.
Relevant PR: https://github.com/BHoM/ETABS_Toolkit/pull/281
A note is due to the input param name change on the adapter, the wire connectivity is lost
and this will not update the EtabsConfig components, only the ETABSAdapter
https://burohappold.sharepoint.com/:u:/s/BHoM/Ee2kdsVhG_xAv3HBDL3RvYIBwjjyI0XoaPWHyOy2SXjLLg?e=NIVO2H
> Type Converter for ETABS PR281

- BHoMUpgrader32/App.config
- BHoMUpgrader32/BHoMUpgrader32.csproj
- BHoMUpgrader32/MethodConverter.cs
- BHoMUpgrader32/ObjectConverter/_Interface.cs
- BHoMUpgrader32/Program.cs
- BHoMUpgrader32/Properties/AssemblyInfo.cs
- BHoMUpgrader32/TypeConverter.cs
- Versioning_Toolkit.sln
Closes #53
This is literally a copy-paste of upgrader 3.1 where I changed the version number and emptied the dictionaries. 
Take any file that requires a component to be upgraded and make sure that this is still working. Without this PR, you get a warning that BHoMUpgrader32.exe cannot be found.
If you don't have a script, you can find one here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit?csf=1&e=76MDTD
> Add upgrader for 3.2

- BHoMUpgrader/Upgrader.cs
The key change in this PR is the fact that upgrading a type that doesn't have any versioning information is now returning null (like for object and method) instead of the input type. Otherwise, simply making sure that methods can update their internal types through the chain.
Any old file you have at hand. See more links from https://github.com/BHoM/Versioning_Toolkit/pull/66
- Fix recursive triggering not happening for Old mode of serialisation 
- Fix Method upgrader reporting false "modified" types
- Upgrader now calling upgrade methods recursively for sub types
> Improve BHoM Upgrader handling of types

- Versioning_oM/Versioning_oM.csproj
Closes #73
I have only fixed Versioning_oM as the other projects are not compiling into the Build folder directly. 
Make sure that the Build folder only contains versioning dlls after compiling (make sure you deleted its content before testing).
> Fix Compliance issue for CSProj files

- BHoMUpgrader32/Converter.cs
https://github.com/BHoM/BHoM/pull/912
Adds in `ModeNumber` as a property to structural results, if not found in the initial dictionary.
This is needed for the serialiser to be able to apply the correct creator map when trying to deserialise the results.
https://burohappold.sharepoint.com/:f:/s/BHoM/Ep9h3lEyopBBvsnP3_HGzSwBncLyPKvZnn0q6AZBwMRwzA?e=j5DdEe
> Add versioning to Structural results

- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader33/Converter.cs
- PostBuild/CopyUpgrades.cs
Does not depend on, but done together with:
https://github.com/BHoM/BHoM/pull/959
https://github.com/BHoM/BHoM_Engine/pull/1916
Closes #88 
Closes #89 
See https://github.com/BHoM/BHoM/pull/959 for test of Framing element upgrades
For General versioning test, see:
https://burohappold.sharepoint.com/:f:/s/BHoM/EopxQb5d9QdDqKoD--1178kBUpVHnKPZ1WWwyI2Eg1l18Q?e=1mkQkS
- Adds versioning for FramingElements and ConstantFramingProeprty from Structure_oM to Phsyical_oM, including slight obejct restructure
- Fix issue in postbuild, not allowing for more than one previous attribute
- Fix order ObjectUpgrade is preformed, to make sure full convert methods in the toolkit is prioerities, if they exist, over simpler type upgrade
> Add versioning for FramingElements, fix bug in PostBuild and fix order of ObjectUpgrader

- BHoMUpgrader/Upgrader.cs
Closes #91 
Fixes a bug where the Property name upgrades got assigned the name of the class, including namespace + the new property name. Now changed to only pick out the last value.
Can be tested with https://github.com/BHoM/BHoM/pull/961
> Make sure property name is only last word, not including type name

- BHoMUpgrader/Converter.cs
There was a type in the code that meant that a conversion entry in the Type dictionary that was supposed to be on `ToOld` ended up in `ToNew`, potentially creating infinite loop in very rare cases.
This one should be pretty obvious to review but shout if you disagree.
> Fixing Type collection error for versioning

- BHoMUpgrader33/Upgrades.json
- BHoMUpgrader40/App.config
- BHoMUpgrader40/BHoMUpgrader40.csproj
- BHoMUpgrader40/Converter.cs
- BHoMUpgrader40/Program.cs
- BHoMUpgrader40/Properties/AssemblyInfo.cs
- BHoMUpgrader40/Upgrades.json
- Versioning_Toolkit.sln
Closes #94
Getting the versioning toolkit ready for transition to BHoM 4.0.
You can find the procedure for this PR here: https://github.com/BHoM/Versioning_Toolkit/wiki/End-of-milestone-procedure
Simply compile the versioning toolkit and make sure versioning is still working fine. I recommend:
- Create a fake `Versioning_44.json` in one of your project to make sure its content got captured into the final upgrader 4.0 `Upgrades.json` file.
- you run this twice: once without deleting the content of the Upgrades folder created by the installer and once by first deleting it.
Note that this will only work when the assembly versions have all been migrated to 4.0
> Migrate to version 4.0

- BHoMUpgrader40/Converter.cs
https://github.com/BHoM/BHoM/pull/1121
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue1070-RemoveEmbodiedCarbonFromMaterialFragments?csf=1&web=1&e=A2B66W
- Added versioning for `MaterialFragments` for 4.0 and beyond
> Align with changes to Structure_oM with removal of EmbodiedCarbon from MaterialFragments

- BHoMUpgrader40/Converter.cs
Closes #113
File created on 3.3 Beta uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FVersioning%5FToolkit%2F%23113%2DRevitToolkitTypeVersioning%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FVersioning%5FToolkit) - after the fix, the objects should not be `CustomObjects` any more.
- versioning added for `BH.oM.Adapters.Revit.Settings.FamilyLoadSettings`
> Versioning added for FamilyLibrary

- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader40/Converter.cs
Follow up on https://github.com/BHoM/BHoM_Engine/pull/2241
As mentioned in that PR, the `BH.oM.Environment.Elements.Space` objects from version 3.2 crashe the UI after the PR was merged. Since the problem occurs only for the `Space` class, I decided to fix its upgrader instead of finding an alternative solution to what was removed by that PR. 
Overall, the problem we are facing right now will be solved once we switch to forward versioning so I think this is good enough for the beta as versioning will be frozen for 4.0 anyways. So no risk of new types upgrades creeping up. 
Also notice, I have added a tiny change on the `Upgrader` code. This is because I noticed that the upgrader from previous versions were not called as often as they should have. The problem was that the new code added …
> Fix Upgrader for Space

- BHoMUpgrader41/Converter.cs
https://github.com/BHoM/BHoM/pull/1173
https://github.com/BHoM/BHoM_Engine/pull/2286
https://github.com/BHoM/CSharp_Toolkit/pull/41
See https://github.com/BHoM/BHoM/pull/1173
There is no support for the removal of a property right now. It is actually super easy to add that feature by replacing a property name with an empty string in the local versioning files. Since the Versioning toolkit is properly blocked right now, I just did a custom converter instead (I cannot edit the Upgrader.cs file right now). This creates no clash since this is only changing the content of the `BHoMUpgrader41/Converter.cs` file.
Try to deserialise this:
```
{ "_t" : "BH.oM.Programming.DataParam", "BHoM_Guid" : "306e42e5-4b12-49f0-ba05-cc8b3d7b53b0", "Name" : "test", "Fragments" : [], "Tags" : [], "CustomData" : …
```
> Add versioning for the removal of ParentId in INodeParam

- BHoMUpgrader43/Converter.cs
https://github.com/BHoM/BHoM/pull/1255
https://github.com/BHoM/BHoM_Engine/pull/2528
Closes #168 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Versioning_Toolkit/%23168-ConcreteSectionUpgrade.gh?csf=1&web=1&e=YqA4Bo
- Added versioning for `ConcreteSection` to maintain the `Reinforcement` and `MinimumCover` when upgrading to `BarRebarIntent` objects
> Add versioning for ConcreteSection objects

- .ci/code/Versioning_Test/Helpers/CanReplaceMethodWithType.cs
Closes #180
Fixing two issues with the fallback type
- Fixes the grouping by namespace to make sure adapter namespaces are appropriately grouped
- Changing the checking of exact match or StartsWith to instead splitting by generics sign and only check for exact match
https://burohappold.sharepoint.com/:f:/s/BHoM/EjFXfSKJ2mlNmQMbHWWXH4sBwNWOSNPgpdK3uhRk4v1jfw?e=ZcswlC
> Fix issues with verification for fallback type

- .ci/code/Versioning_Test/Verify/FromJson.cs
Aims to speed up Versioning checks on PRs by allowing only the latest version to be tested against, with all versions saved for overnight builds.
> Enable Versioning checks to decide between running all versions or just the latest

- BHoMUpgrader60/Converter.cs
https://github.com/BHoM/BHoM/pull/1423
https://github.com/BHoM/BHoM_Engine/pull/2897
https://github.com/BHoM/Revit_Toolkit/pull/1266
Add custom upgrader for RevitMaterialTakeoff to new VolumetricMaterialTakeoff class
> Add custom upgrader for RevitMaterialTakeoff

- BHoMUpgrader60/Converter.cs
Closes #206 
Many things changed in source PR, though only minor changes to objects between versions requiring conversion here.
- Added Converter methods for LBT_Toolkit Shelter and Typology objects
Do not merge LadybugTools_Toolkit branch - it should be deleted once this PR gets tested & approved!
> Added LBT 5.3 converter methods

- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader60/Converter.cs
> Versioning of XML PR

- PostBuild/CopyUpgrades.cs
Closes #191
1. Switch Revit_Toolkit to branch with the same name as this
2. Build Revit_Toolkit in a few solution configs
3. Build Versioning_Toolkit
4. Check if C:\ProgramData\BHoM\Upgrades\BHoMUpgrader52\Upgrades.json contains `Method.ToNew.TestMethod`
Actual versioning will of course only work in the Revit context - but this PR is meant to enable capturing the attributes from Revit assemblies and putting their owners in Upgrades.json, no more than that.
**Do not merge Revit_Toolkit branch** - it should be deleted once this PR gets tested & approved!
> PostBuild tweaked to allow versioning of the Revit assemblies

- BHoMUpgrader/Upgrader.cs
Closes #260
Turns off the console logging by default. More critical for console apps as the versioning is now called directly, leading to an bombardment of versioning logging drastically slowing the upgrader down. When ProcessingLoop is called, the logging is turned on, as this is only done when the versioning is run as a standalone .exe with its own log, and not affecting the main log of any application.
> Turn off console logging by default

- BHoMUpgrader/BHoMUpgrader.csproj
- BHoMUpgrader/Converter.cs
- BHoMUpgrader/Upgrader.cs
- BHoMUpgrader73/BHoMUpgrader73.csproj
Closes #265
Theoretically it should be enough if versioning check passed, but I also added a super simple manual test: just build [this branch](https://github.com/BHoM/BHoM/tree/Test-Versioning_Toolkit-%23265-AvoidCopyingBHoMAssemblies) => rebuild BHoM and Versioning_Toolkit => check if _C:\ProgramData\BHoM\Upgrades\BHoMUpgrader73_ gets populated as expected => run script from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FVersioning%5FToolkit%2F%23266%2DAvoidCopyingBHoMAssemblies).
> Avoid copying BHoM assemblies to BHoMUpgrader folder

- BHoMUpgrader/Upgrader.cs
Closes #283
There is no easy way to test this PR to full extent. The easiest way is to locally run versioning tests for all versions, which I did and can confirm the numbers do not change.
However, as discussed with @IsakNaslundBh it is worth digging deeper to see if the versioned objects come out the same before & after the change. I did this by modifying the versioning code locally to dump all explicitly versioned objects into a log, results uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FVersioning%5FToolkit%2F%23284%2DExplicitUpgradeFix) together with explanation of differences between `develop` and this …
> Explicit upgrade fixed to occur before the properties get upgraded

- BHoMUpgrades/CustomUpgrades/v82.cs
https://github.com/BHoM/BHoM/pull/1641
https://github.com/BHoM/LifeCycleAssessment_Toolkit/pull/357
Add versioning for metrics and results, removing MetricType no longer a property.
> Add versioning for metrics and results
